// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/1/2025, 6:52:19 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/myles.enriquez/dev/experiment/challenge-me/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/myles.enriquez/dev/experiment/challenge-me/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/myles.enriquez/dev/experiment/challenge-me/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/myles.enriquez/dev/experiment/challenge-me/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/myles.enriquez/dev/experiment/challenge-me/plugins/**/*.{js,ts,mjs}","/Users/myles.enriquez/dev/experiment/challenge-me/composables/**/*.{js,ts,mjs}","/Users/myles.enriquez/dev/experiment/challenge-me/utils/**/*.{js,ts,mjs}","/Users/myles.enriquez/dev/experiment/challenge-me/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/myles.enriquez/dev/experiment/challenge-me/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/myles.enriquez/dev/experiment/challenge-me/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/myles.enriquez/dev/experiment/challenge-me/app.config.{js,ts,mjs}"]}},
{"darkMode":"class","theme":{"extend":{"colors":{"dark-bg":"#111","dark-card":"#222"}}}}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;